name: Deployment

env: 
  DART_VERSION: "3.x"
  DART_CHANNEL: "stable"
  FLUTTER_VERSION: "3.x"
  FLUTTER_CHANNEL: "stable"
  PACKAGE_NAME: "package_name"

on:
  push:
    branches:
      - "main"
jobs:
  renterd_testing:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./packages/${{env.PACKAGE_NAME}}/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout Flutter Actions
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: ${{env.FLUTTER_CHANNEL}}
          
      - name: Renterd testing
        run: |
          # flutter pub get
          # flutter analyze
          # flutter test